name: Deploy (Stubbed)

on:
  push:
    branches: [ astro ]
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployment temporarily stubbed. Restore previous YAML to re-enable publishing."
